[workspace]
members = ["day-*/"]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.80"

[workspace.lints.clippy]
pedantic = "warn"

[profile.release]
lto = true
codegen-units = 1
strip = true
